### ISSUE TITLE
[ENVIRONMENT] 도메인 구조 설계 및 엔티티 클래스 작성 

### ISSUE THREAD

**Issue by kmw10693** [KU-rum/backend#3]
### 📄 Describe

프로젝트의 전체 구조를 정하고 논의한 ERD를 기반으로 엔티티 클래스를 생성해 놓으려 합니다.

### ✅ Tasks

- 엔티티 클래스 작성

### 🙋🏻 More

누락되어 있는 엔티티 있으면 코드 리뷰 해주세요!

**Comment by Hyeri1ee** [comment]
`유저:학과` 가 현재 `N:1` 매핑으로 되어있는데, 다전공,부전공인 경우를 고려해서 `1:N`으로 바꾸는 게 낫지 않을까요?

**Comment by Hyeri1ee** [comment]
기능명세서에 공지 홈페이지에 대해 `- 카테고리 별로 선택할 수 있도록 하기` 가 있어서

1. 사용자가 즐겨찾기한 공지사항 카테고리를 모아놓는 새로운 테이블과

2. 지금 공지사항 테이블에 카테고리 필드도 추가해야 될 것 같습니다

**Comment by kmw10693** [comment]
> `유저:학과` 가 현재 `N:1` 매핑으로 되어있는데, 다전공,부전공인 경우를 고려해서 `1:N`으로 바꾸는 게 낫지 않을까요?

한 학과에는 다수의 유저를 받고, 다전공까지 고려했을 때, 한 유저가 다수의 학과를 가지니 'M:N' 관계가 맞을 것 같습니다!
이 'M:N' 관계를 분할하기 위해서, 전공 테이블(학번(PK,FK), 학과ID(PK2, FK), 전공구분코드(1전공, 2전공, 3전공, 부전공, 복수전공 등))을 만드는게 나아보입니다! 전공 구분코드를 만든 이유는, 만약에 3전공을 하는 학생이 있는 경우, 전공이 늘어날때마다 컬럼이 늘어나기 때문입니다.

따라서 전공 테이블에서
학번 / 학과 / 전공구분
202112322 / 스마트ICT융합공학과 / 부전공 

이런식으로 저장하면 어떨까요?

**Comment by kmw10693** [comment]
> 기능명세서에 공지 홈페이지에 대해 `- 카테고리 별로 선택할 수 있도록 하기` 가 있어서
> 
> 1. 사용자가 즐겨찾기한 공지사항 카테고리를 모아놓는 새로운 테이블과
> 2. 지금 공지사항 테이블에 카테고리 필드도 추가해야 될 것 같습니다

네 알겠습니다! 즐겨찾기 테이블, 공지사항 테이블에 카테고리 필드도 추가하겠습니다!

**Comment by Hyeri1ee** [comment]
> 따라서 전공 테이블에서 학번 / 학과 / 전공구분 202112322 / 스마트ICT융합공학과 / 부전공

네 M:N 관계가 맞는 것 같네요! 좋습니다 😄
